### ISSUE TITLE
Export to PPT/PDF is not supported. Please enhance the visual to support export functionality

### ISSUE THREAD

**Issue by akhilduvvuru** [dm-p/powerbi-visuals-html-content#101]
**Is your feature request related to a problem? Please describe.**
<img width="269" alt="Screenshot 2023-12-20 at 12 43 34 PM" src="https://github.com/dm-p/powerbi-visuals-html-content/assets/51473749/6c10c1c3-7358-481f-a100-11b70137c06c">
It would be good if we have option to export to PPT/PDF

Exporting is the issue. 
**Describe the solution you'd like**

Please enhance to visual to support export functionality

**Comment by dm-p** [comment]
Hi, and thanks for raising. The standard edition of the visual cannot support exporting as it is not certified. It cannot be certified due to the functionality on offer.

You can use the certified edition - [HTML Content (lite)](https://appsource.microsoft.com/en-us/product/PowerBIVisuals/coacervolimited1596856650797.htmlcontent_certified), which comes with some limitations due to requirements from Microsoft for certified visuals. Please refer to the site for more details:

https://www.html-content.com/editions

https://www.html-content.com/faq
