### ISSUE TITLE
[BUG] Visual is not supported in PDF export

### ISSUE THREAD

**Issue by LS-Stud** [dm-p/powerbi-visuals-html-content#109]
Hi Daniel,

Thanks again for providing this HTML visual!

By creating an pdf export of the report, which I previously published to my online Power BI workspace, I ran into the bug, that the visuals content cannot be exported.
The error message in the exported report is "This visual does not support export" (in German: Dieses Visual unterstützt keinen Export.")

![image](https://github.com/dm-p/powerbi-visuals-html-content/assets/60919765/366e02cd-8c61-48f0-995f-de8eac305371)

I'd really appreciate your help with this improvement.

Many thanks in advance!

Best regards!

**Comment by dm-p** [comment]
This is expected behavior and not a bug. The regular version of HTML Content is not certified and as such cannot export to PDF. You will need to use [HTML Content (lite)](https://appsource.microsoft.com/en-us/product/PowerBIVisuals/coacervolimited1596856650797.htmlcontent_certified) for this functionality.

Please note that the certified version has less functionality in order to be compliant with MS certification rules. You can read more about what is possible on the [website's Editions page](https://www.html-content.com/editions). [Additional details are also in the FAQ](https://www.html-content.com/faq).
