### ISSUE TITLE
[BUG] links sources from same Sharepoint source data is stored are being truncated

### ISSUE THREAD

**Issue by Annaleesa** [dm-p/powerbi-visuals-html-content#110]
**Describe the bug**
The data I’m pulling is in Lists which is stored in my Company’s SharePoint. I’m using the html viewer to show links from one of the columns in Lists. Whenever the link is to something else stored in my company’s SharePoint, it truncates the link to drop off the “https://companyname.sharepoint.com”. I think it’s because that is the same link as the data source for the Power BI report. I’ve checked the Power BI settings along with my company’s security settings and neither should be interfering. Is it possible the truncating issue is sourced from the html viewer itself?

**To Reproduce**
I’ll select the link in the html viewer and it will state “Cannot Open in Web Browser. The link is malformed” and will show the truncated link. 

**Expected behavior**
The link to open without truncating. It did this when I had the Power BI report in my personal Workspace, but stopped working once I moved the report to the company SharePoint where the links are also sourced. 

**Screenshots/Workbook**
Pop-up when I try to open URL in old report:
![image](https://github.com/dm-p/powerbi-visuals-html-content/assets/10378096/a64f3b29-1665-4333-8306-cd2fb9658180)

Pop-up when I try to open the same URL in new report stored in SharePoint:
![image](https://github.com/dm-p/powerbi-visuals-html-content/assets/10378096/d0ed8944-b9ed-478a-84e1-50c66fccc105)

Unsure if the visuals actually took, if not, here’s the link to where I posted about it in another forum including the same screenshots: 

https://community.fabric.microsoft.com/t5/Desktop/HTML-Viewer-dropping-off-SharePoint-part-of-URL-and-Erroring/m-p/3880382#M1249137

**Power BI Setup (please complete the following information):**
 - Platform: Power BI Desktop app and on web
 - OS: Windows 11 Enterprise 22000.3019
 - Browser: Chrome
 - Version 126.0.6478.127

**Visual Information (please complete the following information, available by right-clicking the visual in Power BI and selecting *About*): HTML Content
 - Version: 1.5.0.0

**Additional context**
Other links are able to open, it’s only when the link is sourced from the same SharePoint the Power Bi data is being sourced from

**Comment by dm-p** [comment]
Thanks very much for raising. This sounds like the column you're supplying to the visual for the hyperlink contains a relative URL? If so, this is not valid for what Microsoft allows in custom visuals: [all hyperlinks have to be fully qualified with either the HTTP or HTTPS protocol](https://learn.microsoft.com/en-us/power-bi/developer/visuals/launch-url#considerations-and-limitations:~:text=Use%20only%20absolute%20paths%2C%20not%20relative%20paths.%20For%20example%2C%20use%20an%20absolute%20path%20such%20as%20https%3A//some.link.net/subfolder/page.html.%20The%20relative%20path%2C/page.html%2C%20won%27t%20be%20opened.).

For a relative URL, you must append a suitable protocol and server to the URL (ideally as far upstream as possible, e.g., Power Query) so that Power BI can resolve it on your behalf (we have to submit URLs to Power BI to delegate; custom visuals are not allowed to open hyperlinks themselves).

If the dataset contains a fully qualified URL that is being supplied to the visual correctly and then somehow truncated afterward, this shouldn't happen and is indeed a bug. In that case, I will need to see suitable data that reproduces the issue. If you can provide a sample .pbix or dataset, this will be a great help. Including the dataset in a separate table,visual is also useful, so it's easier to inspect the raw values in the context of the data model. If these are correctly prefixed with `http(s)://` in the visual table, then they should be represented similarly in HTML content.

**Comment by Annaleesa** [comment]
I have the data stored in SharePoint Lists, but I have it exported to excel with an example for you to view. I also took a screenshot of the Power BI report attempting to open the same link as shown in the example in column G titled Notes1. The Lists data the Power BI report is sourcing from is also stored in the same place "https://tmobileusa.sharepoint.com/sites/" and is what keeps getting truncated from these links I'm attempting to have opened.

**Comment by Annaleesa** [comment]
I'm having issues attaching the screenshot and excel file so I will email them to you separately.

**Comment by Annaleesa** [comment]
Is there an update on this? Did you receive the screenshot and excel file I emailed?

**Comment by dm-p** [comment]
Hi @Annaleesa - yes, apologies. I had all kinds of issues with sensitivity labels not allowing me to look at the document, and I parked it for later due to having a lot of things on my plate. I took a look this morning and found a way around the issue so I've been able to have a look.

I set up a measure as follows:

```
Test  URL = 
    VAR _URL = MAX ( Sheet1[Notes1] )
    RETURN "<a href=""" & _URL & """>" & _URL & "</a>"
```

I added this to my visual's **Values** role and enabled the _Allow opening URLs_ setting. Clicking the link gets me the dialog to open a URL, as I expect:

![image](https://github.com/user-attachments/assets/e66f3c0a-30d0-4ec2-a502-304b003d6337)

To confirm, the generated HTML is a valid URL, e.g. enabling the _Show raw HTML_ property:

![image](https://github.com/user-attachments/assets/14bae40b-a044-487f-ab26-d40b093daab6)

I notice in the screenshot you sent, the error is as follows:

![image](https://github.com/user-attachments/assets/779d1fc5-7fb8-42dd-b9e2-365f5eab2847)

Can I check if you are binding this text to the link's `href` attribute? If so, this will indeed not work, as there is not a valid HTTP(S) protocol in the URL that Power BI is attempting to open.

**Comment by dm-p** [comment]
This was investigated further offline, and the root cause was the `href` attribute containing a relative URL rather than the fully qualified one. Replacing the `href` attribute with the fully qualified URL (including `https` protocol) will cause Power BI to prompt/open the hyperlink as MS requires it to be provided to the main window.
