### ISSUE TITLE
[ENHANCEMENT] - A button to allow for auto formatting

### ISSUE THREAD

**Issue by MikeCarlo** [dm-p/powerbi-visuals-html-content#19]
**description**

I would like a button in both the Body HTML Template and Stylesheet that when pressed would auto format the code in the editing window.

I don't write the best code and thus, when I need to review or look at why I screwed up my HTML it is helpful to see the proper indentations. 

![image](https://user-images.githubusercontent.com/25160592/99841957-99967400-2b34-11eb-8d65-75cb89f71a5f.png)

**Comment by dm-p** [comment]
Current thoughts (to cover off multiple use cases):
* Allow format operation while editing, without Applying changes (above request)
* Add property to auto-format when Apply clicked

**Comment by dm-p** [comment]
This is resolved in build 2.0.0.64.

For example, if we have the following HTML:
![image](https://user-images.githubusercontent.com/10572054/101566296-9e638f00-3a33-11eb-9939-a9b1824d7a20.png)

We can click the **Auto-Indent** button and this will pretty-print the HTML, e.g.:
![image](https://user-images.githubusercontent.com/10572054/101566357-bc30f400-3a33-11eb-9b05-80ceb4ae51a9.png)

The user will need to click **Apply** after reviewing changes.

This will auto-indent according to the value of the *Tab Size* property in the *Advanced Editor Options* menu.

This logic is centralised in the HTML Content Visual API, so the *Show Raw HTML* property will use the same logic and properties to generate its output.

Note that this is not enabled for the Stylesheet, due to limitations of using Handlebars (`{{ }}`) syntax in there, as all braces are treated as a nested property, then auto-indented and this breaks any syntax. The Stylesheet will need a bit more thought in-general, as the Handlebars syntax mode doesn't work well with pure CSS - it needs to be inside an HTML `<style>` element (even then, the pretty-print doesn't work if using Handlebars helpers). 

I'll create another issue to track improvements to the Stylesheet templating, as I think these changes satisfy @MikeCarlo's particular use case.
