### ISSUE TITLE
[ENHANCEMENT]  - Re-Attempt Monaco Editor Integration

### ISSUE THREAD

**Issue by MikeCarlo** [dm-p/powerbi-visuals-html-content#20]
not sure if this is possible, But I would like to use the rich editing of Visual Studio Code to edit my text. 

I would like to have a button or an icon that would enable me to open my Body HTML Template or Stylesheet with visual studio code.

![image](https://user-images.githubusercontent.com/25160592/99842156-ee39ef00-2b34-11eb-9cf1-4f791682a8a8.png)

When clicked the current code in the window would be opened in Visual Studio Code. 

![image](https://user-images.githubusercontent.com/25160592/99842226-0f024480-2b35-11eb-8df4-05e44f1f2540.png)

as far as getting code back into the editor, I would be ok just using copy and paste to return to the HTML content visual.

**Comment by dm-p** [comment]
To open something in VS Code (using the `vscode://`  protocol, we can only use a known file path or URL. Because custom visuals aren't allowed to download files due to the sandbox, the only possibility might be using a data URL, e.g. (for the current default Body HTML Template):
```
vscode://data:text/html;base64,l,PGRpdiBjbGFzcz0iaHRtbENvbnRlbnRCb2R5Ij4KCXt7I2VhY2ggcm93c319CgkJPGRpdiBjbGFzcz0iaHRtbENvbnRlbnREYXRhUm93Ij4KCQkJe3tbcm93XX19CgkJPC9kaXY+Cgl7ey9lYWNofX0KPC9kaXY+
```
...but I've just tried this and while it prompts for me to open via VS Code, it actually won't open it.

A couple of other things to consider:
* If we could open the text, it wouldn't have any auto-completion for data or helpers
* We couldn't save changes back to the visual once we were done

Fun fact: I originally started by embedding Monaco (the editor that VS Code uses) into the visual, but it has some architectural challenges, due to how it dynamically scales up and down for performance by loading web workers. I'll take another look at this, as it would be my ideal preference rather than Ace Editor.
