### ISSUE TITLE
Add Export to PowerPoint or PDF [ENHANCEMENT]

### ISSUE THREAD

**Issue by rudzimj** [dm-p/powerbi-visuals-html-content#37]
I'm not a fan of the Export to PowerPoint or PDF from PowerBI.com, but some of my users like it. When you export the HTML visual, it prints a shield with an X on it.

![image](https://user-images.githubusercontent.com/36211641/115560391-88d46080-a282-11eb-8f00-7c687a427ea0.png)

It would be great if the visual could be exported. If this is another limitation by the Power BI service, can you add this to the list of restrictions?

**Comment by dm-p** [comment]
Hi @rudzimj - this is indeed not possible due to the visual being uncertified. This specific limitation isn't explicitly flagged in the documentation though, so thanks for flagging it. [I have updated accordingly](https://www.html-content.com/reference/limitations):

![image](https://user-images.githubusercontent.com/10572054/115612167-12e1ff00-a33f-11eb-8ec0-153773e7a7bd.png)

**Comment by dm-p** [comment]
I was combing through previous issues and thought I could at least provide an update on this, in case anyone comes across it. [We now have HTML Content (lite)](https://appsource.microsoft.com/en-us/product/PowerBIVisuals/coacervolimited1596856650797.htmlcontent_certified), which is a certified version of HTML Content, but with more restrictive permissions on what you can render.

**Comment by rudzimj** [comment]
It is beautiful... our HTML content now prints! You are a rock star and my favorite Power BI developer!
