### ISSUE TITLE
[BUG] Visual not appearing in Visualisations custom palette

### ISSUE THREAD

**Issue by nzdaven** [dm-p/powerbi-visuals-html-content#44]
I had this visual in an existing report, but this last week when opening it in PowerBI desktop, the instances of the visual aren't rendering. They still appear when the report is published. 
The icon for html content has disappeared from the palette, and if I click on one of the blank visuals I do not get the configuration pane for the visual. 
I tried adding the visual from the marketplace and from a downloaded file. PowerBI tells me that it is already installed and offers to refresh it. This makes no difference. 
I tried creating a brand new report and adding the visual from the marketplace. It says it is installed, but no icon appears in the palette. 

**Power BI Setup (please complete the following information):**
 - Platform: PowerBI Desktop
 - OS: Windows 10
 - Browser: Edge
 - Version 2.88.721.0 64-bit (December 2020)

**Visual Information (please complete the following information, available by right-clicking the visual in Power BI and selecting *About*):**
 - Version: [e.g. 2.0.0.0] - unfortunately due the bug, I cannot get this information. However the file name is htmlContent.htmlContent443BE3AD55E043BF878BED274D3A6855.1.1.0.15

**Comment by dm-p** [comment]
Hi - any visuals from AppSource are served/updated from there by Power BI, so if it's not appearing then that suggests a transient issue with comms to AppSource from Power BI Desktop. Can you confirm if any other visuals from AppSource will add to your report? Sometimes Power BI 'forgets' there is a connection to AppSource and will not load visuals or sign in to the Power BI Service. This seems to be a recent issue.

If this is the case, it's not specific to HTML Content and you may need to do a log out/in or reboot to fix Power BI Desktop's network connection to AppSource.

**Comment by nzdaven** [comment]
Thanks for your quick response Daniel, other visuals from AppSource are loading fine with their icons displaying in the visualisations palette. 
I did have a go at logging out and in again, but no effect as yet.

**Comment by dm-p** [comment]
OK - thanks very much for letting me know.

It's very possible then that the version of Desktop could be the issue. I notice that you're using December 2020, and the HTML Content visual was recently updated to 1.2.0. As part of submitting updates I need to ensure that the visuals libraries are up-to-date so that they are confirmed to work in the latest versions of Power BI by MS. These libraries are packaged into Power BI Desktop at that point in time, and are automatically updated in the Service, which may explain why it's working there but not in Desktop for you. 

Unfortunately MS only allows us to serve the latest version from AppSource, so the ideal solution is to update Power BI Desktop to at least April 2021.

If you're not able to update Power BI Desktop (I'm aware some companies do this centrally and mandate a particular version for various reasons), there's a couple of options:

* I make a standalone version of the visual available that is not linked to AppSource, in the releases - [here's the link for 1.1.0](https://github.com/dm-p/powerbi-visuals-html-content/releases/tag/1.1.0.15) and you can download the .pbiviz from the assets section. **This is not tied to AppSource**, so you will need to manually manage it across any workbooks you're using it in and will not receive updates automatically.
* Add the .pbiviz to [your tenant's organizational store](https://docs.microsoft.com/en-us/power-bi/admin/organizational-visuals). If you're not an admin then you may need to discuss this with someone who is. The advantage to doing it this way is that you can manage the version of the visual centrally to your organization.

**Comment by nzdaven** [comment]
Yes, the date on my version surprised me. Am checking with our support (updates are centrally managed for us) to see if an update is around the corner. In the meantime, thank you very much for the link to the standalone. I have installed this and it looks to be working so that will get me by until we update, and then I will switch over to the latest form AppSource. 

Thank you so much for your help and have an awesome day/evening!

**Comment by dm-p** [comment]
This issue actually has some wider impacts, i.e. folks using Report Server, as this is further behind in terms of compatibility. So, there's a new version (1.2.1) being submitted with the API changes reverted. [The standalone download is available here](https://github.com/dm-p/powerbi-visuals-html-content/releases/tag/1.2.1.17) if you want to start using it in the meantime.
