### ISSUE TITLE
Visual doesn't show the map in power bi service

### ISSUE THREAD

**Issue by Estefani1995** [dm-p/powerbi-visuals-html-content#48]
[](url)Hi there!

I have an issue, when I publish the visual in power bi service it doesn't show the map. The message that shows is: "Chore blocked this page" as attached image:

<img width="487" alt="Captura" src="https://user-images.githubusercontent.com/93225379/140399093-c8f74f2c-710b-49ab-a8e7-b2644ac8516f.PNG">

I enter in power bi the following DAX Code: HTML = "<iframe src="&CodigoHTML[URL]&" style='position: fixed;width: 100%; height: 100%'></iframe>"

The "CodigoHTML[URL]" is: https://www.dhn.mil.pe/shnaNEW/histogramas_shna/archivos/Pucallpa.pdf

I would want to show that map in  Power Bi, the link never change, but the information that it contains change every day (almost)

I tried to visualize this map by PDF Viewer, but doesn´t update the content even I update the the page of power bi desktop.

Please your help, I'm on this 3 days and don't find an alternative way...

**Comment by dm-p** [comment]
Hi there - this one seems to be specific to Chromium, so doesn't work in Edge either.:

![image](https://user-images.githubusercontent.com/10572054/140416139-1d5afb29-b3d1-41fd-b015-a06640f7b17a.png)

---

Firefox seems OK though:

![image](https://user-images.githubusercontent.com/10572054/140415291-8997ff21-4c9f-4ebf-8096-be5c309cf9dd.png)


---

And, using the `<object>` tag, rather than using `<iframe>` (also using FF; doesn't work in Chrome/Edge):

![image](https://user-images.githubusercontent.com/10572054/140415216-a64fbef4-0176-40b6-9fe0-b4cab2f844bc.png)

---

If I set up the iframe in a standalone web page, (i.e. a .html file) then this works:

![image](https://user-images.githubusercontent.com/10572054/140417872-674f2508-9a6e-4355-9ae0-1270eec4d276.png)

---

As soon as I apply the top-level [restrictions on the visual sandbox that MS impose](https://www.html-content.com/reference/limitations) (`allow-scripts`), this is blocked:

![image](https://user-images.githubusercontent.com/10572054/140417802-d11201b8-0c8e-4c84-9276-4d4ea95cee31.png)

---

I think that there is some specific feature of Chromium that prevents this scenario in sandboxed iframes. The big difference I can see is that Chromium imposes a Referrer Policy on the request, which Firefox does not:

![image](https://user-images.githubusercontent.com/10572054/140418527-b3b5cd89-c803-423a-bd8a-5d6279de5c02.png)

It's hard to find anything definitive as to whether this is the culprit through web searching.

As the sandboxing cannot be overridden, we may be stuck short of changing browser settings for any users that want to view the report.

I'll leave this open to see if anyone more knowledgeable around browser-specific behaviour re: sandboxing and CORS can offer assistance, but having put a couple of hours into this, I suspect that it's not going to be possible at the visual (or HTML document-level) to solve. As this applies to sandboxing (and therefore all custom visuals) it couldn't be done as a dedicated visual either.
