### ISSUE TITLE
Connection issue with sharepoint

### ISSUE THREAD

**Issue by KumudKhandelwal** [dm-p/powerbi-visuals-html-content#57]
Hi developer team,

We want to embed site analytics for a webpage hosted on sharepoint. Something similar to this.
![Connecting to Sharepoint Analytics](https://user-images.githubusercontent.com/64922555/154942373-87436f19-5acc-41e5-b716-e18a07711e3b.png)

As we face some difficulty with accessing this data directly into our Power BI report, we went ahead to use the available custom connector 'HTML Content' and are trying to embed the complete analytics page in our report. But, we are getting the below error.

"**domain.sharepoint.com** refused to connect" even when all the permissions have been provided to the Power BI report. 
![SharepointConnectionRefusal](https://user-images.githubusercontent.com/64922555/154942914-a6536e5c-0975-40d9-a6cb-1ed4e760f181.png)

What can be the best possible solution to make use of this connector to display the webpage hosted on sharepoint in our Power BI report?

Thanks!

**Comment by dm-p** [comment]
Hi @KumudKhandelwal,

Embedding content via iframes in a custom visual will only work if the remote location is CORS enabled. I imagine that SharePoint requires authentication, and custom visuals are not equipped to handle either of these scenarios, due to them being hosted in a sandboxed iframe themselves, with no domain. [The technical limitations of the visual are detailed here](https://www.html-content.com/reference/limitations), and cannot be worked around due to limits that are imposed by Microsoft as part of the Power BI custom visuals architecture. You might be able to confirm this by checking your browser's console for error messages that will state a message along these lines.

My recommendations would be to revisit the possibility of loading the data from SharePoint into your data model, and if this is still not possible, you may need to investigate using [Power BI Embedded](https://docs.microsoft.com/en-us/power-bi/developer/embedded/) to create a web application that can host both types of content and handle the necessary aspects around access and layout.

Thanks very much,

Daniel

**Comment by KumudKhandelwal** [comment]
Thank you Daniel @dm-p . 
I will analyse this further as instructed.
