### ISSUE TITLE
[BUG]- The visual does not support exporting

### ISSUE THREAD

**Issue by tarektm17** [dm-p/powerbi-visuals-html-content#70]
The visual does not support exporting when export to PDF from the power BI service.
![image](https://user-images.githubusercontent.com/81137640/196554615-edd48fc5-6692-4c64-a4e2-f6a1a0b5038e.png)

**Comment by dm-p** [comment]
[The visual is not certified](https://www.html-content.com/faq#will-the-visual-be-certified), so cannot be exported to PDF. 

If you wish to have exporting work, then you will need to use one of the certified HTML visuals, such as [Shielded HTML Viewer](https://appsource.microsoft.com/en-us/product/power-bi-visuals/wa200002144) or [HTML Text Styler](https://appsource.microsoft.com/en-us/product/power-bi-visuals/WA200002071). Note that due to the limitations around what certified visuals are able to do, what you want the visual to display may not be supported by these visuals.
