### ISSUE TITLE
[BUG] Scroll bug in constant place and hiding content

### ISSUE THREAD

**Issue by AviramWeiss** [dm-p/powerbi-visuals-html-content#71]
Hi,
Thank you very much for this component. It's very useful.
In one project, I'm using it to display rich-text, formatted as HTML.
Specifically, the text presented is formatted right-to-left (and then some more formatting, irrelevant to this issue).
When the text is longer than the control's height, a vertical scrollbar is shown, which is great.

However, **the scrollbar is hiding the rightmost part of the content**.

Two suggestions, if you may:
1. When the scrollbar is shown, allocate its own place, outside the content area
2. As a requested feature (not a bug), allow setting scrollbar's location - right or left.

Power BI Setup:
 - Platform: Power BI Desktop + Power BI Report Server
 - OS: Windows 10
 - Browser: chrome

Visual Information :
 - Version: 1.2.1.17

**Comment by dm-p** [comment]
My apologies for the delay in getting to your request. The library we're using did not (at the time) support RTL, but they've since updated this to work if we set the directionality in the stylesheet, e.g.:

```
<CSS> RTL = "body {
    direction: rtl; 
}"
```

Can result in the following output:

![image](https://github.com/dm-p/powerbi-visuals-html-content/assets/10572054/a1a0c3e3-8612-44f5-b637-0da0c1ebc55e)

If this can work for you, I'll add it to the next update that I'm getting ready to submit?

**Comment by dm-p** [comment]
Great - thanks for confirming! This has been added to 1.4 in PR #91, which has been submitted to AppSource and approved this morning. It should take approximately a couple of weeks to reach production.
