### ISSUE TITLE
Iframe reload on click

### ISSUE THREAD

**Issue by AranaNexplore** [dm-p/powerbi-visuals-html-content#79]
**Describe the bug**

The iframe reloads when click on other screen elements

**To Reproduce**

Create a iframe with what ever content, add a visual, for example stacked bar chart with content.
Click on a column
iframe container reloads so the page you navigated is lost

**Expected behavior**

HTML with an iframe should keep the content with out refreshing.

**Screenshots/Workbook**

![powerBI__3](https://user-images.githubusercontent.com/97663132/217814087-2c5298dd-18c1-45d0-b448-67fa99679dcc.gif)

**Power BI Setup (please complete the following information):**
 - Platform: Powe BI Desktop
 - OS: Windows 11

**Comment by dm-p** [comment]
Hi and thanks for raising.

Unfortunately, this is by design. All custom visuals are already an iframe inside a higher-order container. Power BI will re-draw the higher-order container each time an update happens on the canvas, even if interactions are disabled for a particular visual. 

Any content that is passed into the visual itself will get re-rendered, because Power BI has redefined the custom visual's DOM and we have to re-apply the content for it to display for the user. With iframes, this means that the specified URL will re-initialise.

I've done some tests and even if we execute no further code on an update after initialising the iframe, Power BI will just return a blank space for the visual, so there's no way to circumvent it.

Here's a short video demonstrating what happens if we exit the HTML Content visua logic before anything else happens, which may hopefully clarify things further:

https://user-images.githubusercontent.com/10572054/217940952-9b892968-3fab-405e-9269-6faa192bdd72.mp4

**Comment by AranaNexplore** [comment]
Thanks for replying so fast.
Then I'll search for another workaround on my project.
