### ISSUE TITLE
[EMBED] Website no opening on Power BI

### ISSUE THREAD

**Issue by AndreGSL1** [dm-p/powerbi-visuals-html-content#81]
Hi, 
I am using the HTML Content Visual in Power BI.
But I have an issue with the following sites, I am not sure why they are not opening. I would appreciate a hand with this one. 

Below are the sites:
1. WebsiteFlipper = "<iframe width='300' height='200' frameborder='0' scrolling='no' allowfullscreen src='https://arcg.is/1XuWD4'></iframe>"
2. WebsiteGator = 
"<iframe width='800' height='600' frameborder='0' scrolling='no' allowfullscreen src='https://arcg.is/0uqPn8'></iframe>"

Have a nice day,
Best,
Andrea

**Comment by dm-p** [comment]
Hi Andrea,

If you check the embed in the Power BI Service, you can see these errors in the browser console, which indicate the websites you want to embed use features that MS do not allow in any custom visuals, e.g.:

![image](https://user-images.githubusercontent.com/10572054/235568809-53f4e95f-8aba-4f73-bc68-9614491a76fc.png)

There is nothing we can do about this due to the security restrictions that are imposed by MS and as such there's no way to work around it. [This is documented in a bit more detail here](https://www.html-content.com/reference/limitations#what-doesnt-or-might-partially-work).

If you wish to make these sites accessible, the only way to currently do this in Power BI would be to hyperlink to them so that they open in another tab.

Regards,

Daniel
