### ISSUE TITLE
Functionality <form> with Method Post

### ISSUE THREAD

**Issue by Largura** [dm-p/powerbi-visuals-html-content#92]
Functionality <form> with Method Post

**Comment by dm-p** [comment]
Unfortunately it's not possible to allow posting from forms, because MS don't set the [`allow-forms` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#:~:text=allow%2Dforms%3A%20Allows%20the%20page%20to%20submit%20forms.%20If%20this%20keyword%20is%20not%20used%2C%20form%20will%20be%20displayed%20as%20normal%2C%20but%20submitting%20it%20will%20not%20trigger%20input%20validation%2C%20sending%20data%20to%20a%20web%20server%20or%20closing%20a%20dialog.) on the container that houses the custom visual iframe element. We have no control over this permission from inside the visual.

**Comment by Largura** [comment]
ok, thanks
