### ISSUE TITLE
iframe external webpages not loading from Aug 29, 2023 in Power BI.

### ISSUE THREAD

**Issue by AdityaH08** [dm-p/powerbi-visuals-html-content#94]
Hey,

We have been using the amazing HYML content visual in Power BI for a couple of months to access external websites across our reports, but as of Aug 29, 2023 the HTML content visual is unable to access previously accessible websites (e.g.: <iframe src="https://www.html-content.com/&hideNavbar=true"style='position: fixed; width: 100%; height: 100%'></iframe>) on all of our reports and displaying an error message "This website is blocked. Contact the Site owner to fix the issue".

Request to please look into this and suggest any fix/walkaround.

Error Message Screenshot:
![image](https://github.com/dm-p/powerbi-visuals-html-content/assets/143551548/e1eb415e-0b16-4ef2-bb79-027f1cbae563)

**Comment by dm-p** [comment]
Hi there, and sorry to hear you're having trouble. Unfortunately I am not in a position to provide support in the immediate term, due to being required to serve on a jury for a trial in my country.

From a quick inspection, it looks like Microsoft enforces CSP rather than CORS in the latest versions of the visual APIs. These more recent APIs are needed for other features of HTML Content. It is also not possible to downgrade APIs in an AppSource visual either once it has been updated. 

I will need to contact MS for a suitable suggested configuration for web servers to allow comms from an iframe in a custom visual (if this is even possible now) and hopefully they can provide this. If I get any info, I'll pass this on and update documentation accordingly.

For now, you can downgrade to the standalone version 1.2.0 of HTML Content and load this into your report. The .pbiviz is downloadable [from its release page in this repo (at the bottom, under _Assets_)](https://github.com/dm-p/powerbi-visuals-html-content/releases/tag/1.2.0.16).

**Comment by AdityaH08** [comment]
Hello Daniel,

Thank you for your review the bug and offering an workaround. 

All our reports are live without errors using the standalone version of the visual, thank you!!!

**Comment by dm-p** [comment]
Glad to hear :)

I have submitted a case with MS so will hopefully see if there's a way forward for the latest visual APIs and the production version of HTML Content

**Comment by dm-p** [comment]
MS have provided me with a solution, and I'll hopefully implement and test very soon. I'll keep you posted on how this is going.

**Comment by mattgudites** [comment]
I only just started using this visual and I'm having the same issue. Interestingly, downgrading to the 1.20 standalone didn't work for me...  will await further feedback/another release!

**Comment by dm-p** [comment]
Unfortunately, not all websites can be embedded due to technical constraints with both the intended website and what MS allows custom visuals to do in terms of permissions in Power BI. You may well be hitting this case - [it's explained in more detail here](https://www.html-content.com/reference/limitations).

**Comment by dm-p** [comment]
The fix has been submitted to AppSource. Once version 1.4.1 is live, you should be able to use iframes again (in the standard edition; not supported for Lite/certified).

https://github.com/dm-p/powerbi-visuals-html-content/assets/10572054/bee687d6-5494-4171-b85f-74427892847e

**Comment by AdityaH08** [comment]
Thank you Daniel for following up and submitting the fix.
