### ISSUE TITLE
[BUG] Unable to use Segoe (Bold) or DIN

### ISSUE THREAD

**Issue by PBI-David** [dm-p/powerbi-visuals-html-content#95]
Hi Daniel, 

it seems like the font Segoe (Bold) and DIN don't work as a CSS property. I have also tried wf_segoe-ui_bold and that doesn't give the right font either. Any ideas?

Cheers

```

Measure = 
    VAR CSS = "
            <style>
                .test {
                    font-family: Segoe (Bold), wf_segoe-ui_bold ;
                    font-size: 40px;
                    color: #ADCDE9;
                }
                
            </style>"

RETURN
CSS&
"<span class='test'>My Test</span>"
```

**Comment by dm-p** [comment]
The Segoe family behaviour inside custom visuals is pretty weird. Segoe UI Bold and Segoe UI Semibold are not named font families available to the visual sandbox, so naming them as per the font property dropdowns doesn't work the same. You would need to apply the appropriate `font-weight` to them within a custom visual. The following will work:

#### Segoe UI Bold

````
Measure = 
    VAR CSS = "
            <style>
                .test {
                    font-family: ""Segoe UI"", helvetica, arial, sans-serif;
                    font-weight: bold;
                    font-size: 40px;
                    color: #ADCDE9;
                }
                
            </style>"

RETURN
CSS&
"<span class='test'>My Test</span>"
````

![image](https://github.com/dm-p/powerbi-visuals-html-content/assets/10572054/7c6c8f2c-1929-4b3e-90f8-b15cdd7c65c9)


#### Segoe UI Semibold

````
Measure = 
    VAR CSS = "
            <style>
                .test {
                    font-family: ""Segoe UI"", helvetica, arial, sans-serif;
                    font-weight: 600;
                    font-size: 40px;
                    color: #ADCDE9;
                }
                
            </style>"

RETURN
CSS&
"<span class='test'>My Test</span>"
````

![image](https://github.com/dm-p/powerbi-visuals-html-content/assets/10572054/2f4036e1-70d5-4e87-9d6d-96c6b01fd722)

----

DIN isn't passed to the visual sandbox as a valid font. In Deneb we have actually packaged the DIN font as a base64 asset that we can load and therefore access. TBH I'm surprised I haven't done this with HTML Content. I'm not currently planning any more releases, but I can try to find some time to do a minor release with these changes.

**Comment by PBI-David** [comment]
Thanks Daniel. Just an FYI, that applying a font-weight of bold to Segoe UI does not render the same as Segoe (Bold). They're different fonts. Segoe (Bold) is a lot more elegant looking as you can see below. I also seem to get different results to you. 

1. Standard text box Segoe (Bold) 32
2.  .test {
                    font-family: ""Segoe UI"", helvetica, arial, sans-serif;
                    font-weight: bold;
                    font-size: 40px;
                    color: #ADCDE9;
                }

3.  .test {
                    font-family: ""Segoe UI"", helvetica, arial, sans-serif;
                    font-weight: 600;
                    font-size: 40px;
                    color: #ADCDE9;
                }

![image](https://github.com/dm-p/powerbi-visuals-html-content/assets/86846675/1ced9838-2561-4bd6-afc2-ab6ea40595a5)

**Comment by dm-p** [comment]
[In June 2019, MS standardised font size to points rather than pixels](https://powerbi.microsoft.com/en-us/blog/power-bi-desktop-june-2019-feature-summary/#fontSizes), which will be a contributing reason for why they look inconsistent here.

Here's a text box with Segoe (Bold) 32pt (top), and then HTML Content with the title styled the same (Segoe UI Bold, 32). The title is outside the sandbox, so should be the same as the text box. Underneath the title divider is the HTML Content body, with the measure as configured previously, but modified to `32pt` for `font-size`.

![image](https://github.com/dm-p/powerbi-visuals-html-content/assets/10572054/21175385-b8b8-435d-8e66-d0cd4a733913)

For transparency, measure is as follows:

````
Measure = 
    VAR CSS = "
            <style>
                .test {
                    font-family: ""Segoe UI"", helvetica, arial, sans-serif;
                    font-weight: 700;
                    font-size: 32pt;
                    color: #000;
                }
                
            </style>"

RETURN
CSS&
"<span class='test'>My Test</span>"
````

This is HTML Content 1.4 (AppSource version) inside Power BI Desktop (Aug 2023)

As far as I can tell, these look the same across all three instances, although I wear glasses and am approaching middle age ;)

Unfortunately, MS doesn't provide Segoe UI Semibold in the text box as an option, so I can't repeat the test fully, but here's the title and body test repeated:

![image](https://github.com/dm-p/powerbi-visuals-html-content/assets/10572054/44765f82-25bd-4043-a6c9-16e63965e99b)

Modifying your workbook with the font size changes also looks right (to me):

![image](https://github.com/dm-p/powerbi-visuals-html-content/assets/10572054/d2871db9-6e83-4916-9cc8-725e27bc79ab)

...but have attached for your reference.

[Font.Test.pbix.zip](https://github.com/dm-p/powerbi-visuals-html-content/files/12591481/Font.Test.pbix.zip)

If you see differences between the text box and visual title, this is an MS issue. Anything that applies to the visual container is not available to visual developers and Power BI takes care of it.

If HTML Content's body looks different to its title, then we will need to have a look at potentially embedding those fonts, although [MS doesn't permit them to be converted for embedding](https://learn.microsoft.com/en-us/typography/fonts/font-faq#web), so I'll have to progress this with them somehow.

**Comment by PBI-David** [comment]
How bizarre - I still don't see what you see. I have tested on two completely different machines and I get consistent results on both. 

![image](https://github.com/dm-p/powerbi-visuals-html-content/assets/86846675/e705d91e-06ba-4c87-b2bc-3101660fc004)

I can now see that Segoe (Bold) (text box) is the same as Segoe UI Bold (title) which is good and cleared my misunderstanding there. However, the image above still has different fonts and I checked on two machines. 

1. is the text box 
![image](https://github.com/dm-p/powerbi-visuals-html-content/assets/86846675/e320f9bb-42e5-4e8f-b211-ca054d1cdb14)

2. is the HTML 1.4 with a title and html content which should all look identical but the html still renders much chunkier

![image](https://github.com/dm-p/powerbi-visuals-html-content/assets/86846675/df0065d0-4b13-4eb4-a334-9577751a7595)
 
![image](https://github.com/dm-p/powerbi-visuals-html-content/assets/86846675/95aa6c31-28fe-4382-b86e-7ad79b68016e)
```

Measure2 = 
    VAR CSS = "
            <style>
                .test {
                    font-family: ""Segoe UI"", helvetica, arial, sans-serif;
                    font-weight: 700;
                    font-size: 32pt;
                    color: #ADCDE9;
                }
                
            </style>"

RETURN
CSS&
"<span class='test'>Here is a test</span>"
```


Opening your workbook with zero modifications shows me this:

![image](https://github.com/dm-p/powerbi-visuals-html-content/assets/86846675/6fd1bfbc-6c4f-42d4-a5a2-77cb0ff24cb1)

The service shows me the same.

**Comment by PBI-David** [comment]
To be super explicit:

This title is Segoe UI with a bold modifier and renders the same as the HTML content (quite chunky)

![image](https://github.com/dm-p/powerbi-visuals-html-content/assets/86846675/dfdc84b5-68a3-40f4-8be4-884c39b4a445)

This title is Segoe UI Bold (no bold modifier) and renders much thinner than the HTML content
![image](https://github.com/dm-p/powerbi-visuals-html-content/assets/86846675/b1aca286-a4e7-4b31-9716-50ac26dee946)

**Comment by dm-p** [comment]
Here's how it looks like the Service for me:

![image](https://github.com/dm-p/powerbi-visuals-html-content/assets/10572054/50de8050-457d-4d70-9a4d-4f4260eca02a)

I've tried this on 2 different machines (both on Win 11), 2 different versions of Power BI Desktop, 3 different tenants and both AppSource editions of HTML Content (regular and certified), just to be sure.

At this point, I'm genuinely stumped, so we may need more information to come through before I can progress any further.

**Comment by PBI-David** [comment]
Thanks for checking. It is bizarre that we're seeing different things but I agree without my information then nothing can be done from your side. I'll close for now and reopen if anything else occurs to me.

**Comment by PBI-David** [comment]
Can I reopen this as a reminder to package DIN in the next release? This visual is useful for building KPIs and DIN is a standard font for that. Thanks

**Comment by dm-p** [comment]
I have to submit a bug fix release for iframes not working, so I'll add DIN to this build as well before I submit.

**Comment by dm-p** [comment]
1.4.1 has been submitted to AppSource. When this goes live, you will be able to specify either `din` or `wf_standard-font` as a font family to use DIN inside the visual.

https://github.com/dm-p/powerbi-visuals-html-content/assets/10572054/1804103c-bbed-4570-89b8-de01ecb0e5ee
